name: Deploy generatePresignedUrl Lambda

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Zip Lambda files
        run: |
          mkdir build
          cp lambda/generatePresignedUrl.py build/
          cd build
          zip -r ../presignedUrl.zip .

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy to Lambda (generatePresignedUrl)
        run: |
          aws lambda update-function-code \
            --function-name generatePresignedUrl \
            --zip-file fileb://presignedUrl.zip
